/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicaplayerofficial.Telas;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import musicaplayerofficial.Usuario.UsuarioBase;
import musicaplayerofficial.Usuario.UsuarioComum;
import musicaplayerofficial.Usuario.UsuarioVip;


/**
 * Classe da janela onde o usuario realiza o seu login
 * @author cadoafb
 */
public class LoginTela extends javax.swing.JFrame {
    /**
     *
     */
    public static String str;
    private boolean achouUsuario;

    /**
     *
     */
    public static UsuarioBase usuarioLogado;

    /**
     *
     */
    public TelaInicial tela = new TelaInicial();

    /**
     *
     */
    public TelaErro teErr = new TelaErro();

    /**
     *
     */
    public LoginTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
 
        senhaTexto = new javax.swing.JPasswordField();
        loginTexto = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        textoEntrada = new javax.swing.JLabel();
        entrarBut = new javax.swing.JButton();
        complemento = new javax.swing.JLabel();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 210));
        setResizable(false);
 
        senhaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextoActionPerformed(evt);
            }
        });
 
        login.setText("Login:");
 
        senha.setText("Senha:");
 
        textoEntrada.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        textoEntrada.setText("Tem Login? ");
 
        entrarBut.setText("Entrar");
        entrarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButActionPerformed(evt);
            }
        });
 
        complemento.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        complemento.setText("Entre e faça sua própia PlayList!");
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(complemento)
                            .addComponent(textoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entrarBut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(senhaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(loginTexto)))
                        .addGap(275, 275, 275))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(complemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senha))
                .addGap(33, 33, 33)
                .addComponent(entrarBut)
                .addGap(47, 47, 47))
        );
 
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTextoActionPerformed
    /**
     * Adiciona os usuarios do arquivo na árvore
     * depois busca o usuario digitado na arvore
     * @param evt 
     */
    private void entrarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButActionPerformed
        String _u = loginTexto.getText();
        String _s = senhaTexto.getText();
        
        try {
            adicionarUsuarios();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        boolean ehVip = false;
        UsuarioVip tempUser = new UsuarioVip();
        tempUser.setUsuario(_u);
        tempUser.setSenha(_s);
        achouUsuario = bancoArvore.getInstance().getArvore().busca(tempUser) != null;
        
        if(achouUsuario && bancoArvore.getInstance().getArvore().busca(tempUser).getValue().isVip()) { 
            usuarioLogado = new UsuarioVip();
            usuarioLogado.setUsuario(tempUser.getUsuario());
            usuarioLogado.setSenha(tempUser.getSenha());
        }
        else if(achouUsuario){
            usuarioLogado = new UsuarioComum();
            usuarioLogado.setUsuario(tempUser.getUsuario());
            usuarioLogado.setSenha(tempUser.getSenha());
        }
        bancoArvore.getInstance().getArvore().imprimeEmOrdem();
        
        if(achouUsuario) {
            try {
                tela.repoeMusicasUsuario(usuarioLogado.getUsuario());
            } catch (FileNotFoundException ex) {
                System.out.println("Não possui playlists");
            }
                tela.setVisible(true);
        }
        else teErr.setVisible(true);

    }//GEN-LAST:event_entrarButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }

    /**
     * Funcao reponsavel por adiconar os usuarios do arquivo na árvore binária
     * @throws FileNotFoundException 
     */
    private void adicionarUsuarios() throws FileNotFoundException {
        // Variáveis temporárias para armazenar os dados
        String currLogin = null;
        String currPass = null;
        boolean ehVip = false;
        
        // Cria o scanner separando por espaço
        File f = new File("/home/cadoafb/informacoesUsuario.log");
        Scanner fileScanner = new Scanner(f).useDelimiter("\\s");
        
        int lineNumber = 0;

        // Adiciona todos os usuários cadastrados à árvore
        while (fileScanner.hasNextLine()) {
            currLogin = fileScanner.next();
            currPass = fileScanner.next();
            ehVip = fileScanner.nextBoolean();
            
            // Se for VIP cria um UsuarioVip
            if (ehVip) {
                UsuarioBase u = new UsuarioVip();
                u.setUsuario(currLogin);
                u.setSenha(currPass);
                
                // Insere na árvore
                bancoArvore.getInstance().getArvore().insert(u);

              
                // Se não for cria um UsuarioComum
            } else if (!ehVip) {
                UsuarioBase u = new UsuarioComum();
                u.setUsuario(currLogin);
                u.setSenha(currPass);
                
                // Insere na árvore
                bancoArvore.getInstance().getArvore().insert(u);
            }
            lineNumber++;
            fileScanner.nextLine();
        }
        System.out.printf("%d Contas de Usuario(s)\n", lineNumber);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel complemento;
    private javax.swing.JButton entrarBut;
    private javax.swing.JLabel login;
    private javax.swing.JTextField loginTexto;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhaTexto;
    private javax.swing.JLabel textoEntrada;
    // End of variables declaration//GEN-END:variables
}
