/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meubusao.Telas;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import meubusao.entidades.*;
import meubusao.dao.*;
 
/**
 *
 * @author cadoafb
 */
public class TelaInicial extends javax.swing.JFrame {
 
    /**
     * Creates new form TelaInicial
     */
    DefaultListModel<Onibus> modelOnibus = new DefaultListModel<>();
    DefaultListModel<Motorista> modelMotorista = new DefaultListModel<>();
 
    public TelaInicial() {
        initComponents();
 
        DefaultListModel modeloM = new DefaultListModel();
        DefaultListModel modeloP = new DefaultListModel();
        listaOnibus.setModel(modeloM);
        listaMotoristas.setModel(modeloP);
 
        listaOnibus.removeAll();
        listaMotoristas.removeAll();
 
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMotoristas = new javax.swing.JLabel();
        jLabelOnibus = new javax.swing.JLabel();
        addOnibus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaOnibus = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMotoristas = new javax.swing.JList<Motorista>();
        addMotorista = new javax.swing.JButton();
        addLinha = new javax.swing.JButton();
        addPontos = new javax.swing.JButton();
        addPontos1 = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 85));
        setResizable(false);

        jLabelMotoristas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelMotoristas.setText("Motoristas");

        jLabelOnibus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelOnibus.setText("Ônibus");

        addOnibus.setText("Adicionar Ônibus");
        addOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOnibusActionPerformed(evt);
            }
        });

        listaOnibus.setModel(modelOnibus);
        listaOnibus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaOnibusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaOnibus);

        listaMotoristas.setModel(modelMotorista);
        listaMotoristas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMotoristasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaMotoristas);

        addMotorista.setText("Adicionar Motorista");
        addMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMotoristaActionPerformed(evt);
            }
        });

        addLinha.setText("Adicionar Linha");

        addPontos.setText("Adicionar Pontos");

        addPontos1.setText("Adicionar Viagem");

        jButtonAtualizar.setBackground(new java.awt.Color(102, 153, 255));
        jButtonAtualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAtualizar.setText("Atualizar Tabelas");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jMenuSobre.setText("Sobre");
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelOnibus)
                        .addGap(126, 126, 126)
                        .addComponent(jLabelMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addOnibus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPontos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addOnibus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMotorista)
                        .addGap(35, 35, 35)
                        .addComponent(addLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPontos)
                        .addGap(43, 43, 43)
                        .addComponent(addPontos1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
  
    private void listaOnibusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaOnibusMouseClicked
        System.out.println(listaOnibus.getSelectedValue());
        String temp = listaOnibus.getSelectedValue().toString();
        System.out.println(temp);
//        try {
//            p.vaiNaPasta(temp);
// 
//            
//        } catch (IOException ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
//        }
 
    }//GEN-LAST:event_listaOnibusMouseClicked
    /**
     * Deixa visivel a tela de cadastrar um novo usuario
     * @param evt 
     */
    private void addMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMotoristaActionPerformed
//        if(LoginTela.usuarioLogado.isVip()) {
//            AddUsuario addU = new AddUsuario();
//            addU.setVisible(true);
//        }
//        else {
//            DeveSerVIP janela = new DeveSerVIP();
//            janela.setVisible(true);
//        }

        DetalhesMotorista d = new DetalhesMotorista();
        d.setVisible(true);
        System.out.print("cfd");
         
    }//GEN-LAST:event_addMotoristaActionPerformed
    
    private void addOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOnibusActionPerformed
       AddOnibus addo = new AddOnibus(this,true);
       addo.setVisible(true);
    }//GEN-LAST:event_addOnibusActionPerformed

    private void listaMotoristasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMotoristasValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMotoristasValueChanged

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        refresh();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void refreshMotoristas(){
        ArrayList<Motorista> ms = MotoristaDAO.read();
        if(ms.isEmpty()) System.out.println("Motorista Vazio");
        
        modelMotorista.clear();
        
        for(Motorista m: ms){
            modelMotorista.addElement(m);
        }
        
        listaOnibus.updateUI();
    }
    
    private void refreshOnibus(){
        ArrayList<Onibus> os = OnibusDAO.read();
        
        modelOnibus.clear();
        
        for(Onibus o: os){
            modelOnibus.addElement(o);
        }
    }
    
    public void refresh(){
        refreshOnibus();
        refreshMotoristas();
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLinha;
    private javax.swing.JButton addMotorista;
    private javax.swing.JButton addOnibus;
    private javax.swing.JButton addPontos;
    private javax.swing.JButton addPontos1;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JLabel jLabelMotoristas;
    private javax.swing.JLabel jLabelOnibus;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Motorista> listaMotoristas;
    private javax.swing.JList<Onibus> listaOnibus;
    // End of variables declaration//GEN-END:variables
}
